const constants = {
  marqueeContents: [
    "ANDREW SEBASTIAN HARDIANTA ♦ IT STUDENT ♠ ASPIRING SOFTWARE DEVELOPER ★",
    "THANK YOU FOR VISITING MY SITE! :)",
    "DON'T FORGET TO CONNECT WITH ME IN LINKEDIN!",
    "THIS WEBSITE IS MADE USING REACT.JS BY ME :)",
    "FUN FACT: DID YOU KNOW THAT PIGS CAN NOT LOOK UP TO THE SKY?",
    // "FUN FACT: THIS WEBSITE IS MADE UNDER 1 WEEK!",
    "FUN FACT: GIRAFFES ARE 30 TIMES MORE LIKELY TO GET HIT BY LIGHTNING THAN PEOPLE!",
    "FUN FACT: MY FAVOURITE FLAVOUR IN ANYTHING IS CHOCOLATE!",
  ],
};

export { constants };
